# Generated by Django 6.0.7 on 2026-07-24 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specialty', models.CharField(max_length=120)),
                ('license_number', models.CharField(max_length=64, unique=True)),
                ('academic_title', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'ordering': ['staff__department__name', 'specialty'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_number', models.CharField(max_length=64, unique=True)),
                ('blood_type', models.CharField(blank=True, max_length=8, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('medical_history', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['record_number'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField()),
                ('reason', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('scheduled', 'Da dat lich'), ('checked_in', 'Da tiep nhan'), ('completed', 'Hoan thanh'), ('cancelled', 'Da huy')], default='scheduled', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='emrapi.doctorprofile')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('encounter_type', models.CharField(choices=[('outpatient', 'Ngoai tru'), ('inpatient', 'Noi tru'), ('emergency', 'Cap cuu')], default='outpatient', max_length=20)),
                ('status', models.CharField(choices=[('checked_in', 'Da tiep nhan'), ('in_progress', 'Dang kham'), ('completed', 'Hoan thanh'), ('cancelled', 'Da huy')], default='checked_in', max_length=20)),
                ('visit_date', models.DateTimeField()),
                ('chief_complaint', models.CharField(max_length=255)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('treatment_plan', models.TextField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounter', to='emrapi.appointment')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='emrapi.doctorprofile')),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='emrapi.medicalrecord')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=160)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Nam'), ('female', 'Nu'), ('other', 'Khac')], max_length=12)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('citizen_id', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('health_insurance_code', models.CharField(blank=True, max_length=64, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=160, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['full_name'], name='emrapi_pati_full_na_b6fa71_idx'), models.Index(fields=['phone'], name='emrapi_pati_phone_08de43_idx'), models.Index(fields=['health_insurance_code'], name='emrapi_pati_health__752f30_idx')],
            },
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='emrapi.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='emrapi.patient'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='emrapi.encounter')),
                ('prescribed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='emrapi.doctorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine_name', models.CharField(max_length=160)),
                ('dosage', models.CharField(max_length=120)),
                ('frequency', models.CharField(max_length=120)),
                ('duration', models.CharField(max_length=120)),
                ('instruction', models.CharField(blank=True, max_length=255, null=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='emrapi.prescription')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Quan tri vien'), ('receptionist', 'Nhan vien tiep nhan'), ('nurse', 'Dieu duong'), ('doctor', 'Bac si'), ('lab_technician', 'Nhan vien xet nghiem')], max_length=32)),
                ('employee_code', models.CharField(max_length=64, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='emrapi.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role', 'employee_code'],
            },
        ),
        migrations.CreateModel(
            name='ReceptionistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counter_number', models.CharField(blank=True, max_length=30, null=True)),
                ('shift', models.CharField(blank=True, max_length=60, null=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receptionist_profile', to='emrapi.staffprofile')),
            ],
            options={
                'ordering': ['staff__employee_code'],
            },
        ),
        migrations.CreateModel(
            name='NurseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nursing_license_number', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('care_unit', models.CharField(blank=True, max_length=120, null=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_profile', to='emrapi.staffprofile')),
            ],
            options={
                'ordering': ['staff__employee_code'],
            },
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medical_records', to='emrapi.staffprofile'),
        ),
        migrations.CreateModel(
            name='MedicalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('file', models.FileField(upload_to='medical_attachments/%Y/%m/')),
                ('description', models.TextField(blank=True, null=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='emrapi.encounter')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to='emrapi.staffprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabTechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laboratory_unit', models.CharField(blank=True, max_length=120, null=True)),
                ('certification_number', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_technician_profile', to='emrapi.staffprofile')),
            ],
            options={
                'ordering': ['staff__employee_code'],
            },
        ),
        migrations.AddField(
            model_name='encounter',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_encounters', to='emrapi.staffprofile'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='emrapi.staffprofile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_appointments', to='emrapi.staffprofile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to='emrapi.staffprofile'),
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pulse', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('systolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diastolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('respiratory_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='emrapi.encounter')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_vital_signs', to='emrapi.staffprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_name', models.CharField(max_length=160)),
                ('ordered_at', models.DateTimeField(auto_now_add=True)),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ordered', 'Da chi dinh'), ('processing', 'Dang xu ly'), ('completed', 'Da co ket qua'), ('cancelled', 'Da huy')], default='ordered', max_length=20)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='emrapi.encounter')),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_lab_tests', to='emrapi.doctorprofile')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_lab_tests', to='emrapi.labtechnicianprofile')),
            ],
            options={
                'ordering': ['-ordered_at'],
                'indexes': [models.Index(fields=['status'], name='emrapi_labt_status_71d53c_idx'), models.Index(fields=['ordered_at'], name='emrapi_labt_ordered_b6746a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['role'], name='emrapi_staf_role_01444e_idx'),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['employee_code'], name='emrapi_staf_employe_a2f262_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['visit_date'], name='emrapi_enco_visit_d_0ae65e_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['status'], name='emrapi_enco_status_e1b572_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['medical_record', 'visit_date'], name='emrapi_enco_medical_ffb804_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['scheduled_at'], name='emrapi_appo_schedul_d352b0_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='emrapi_appo_status_eaf0b5_idx'),
        ),
    ]
