# Generated by Django 6.0.7 on 2026-07-25 10:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['unit_type', 'name']},
        ),
        migrations.AlterModelOptions(
            name='prescriptionitem',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_units', to='emrapi.department'),
        ),
        migrations.AddField(
            model_name='department',
            name='unit_type',
            field=models.CharField(choices=[('department', 'Khoa'), ('office', 'Phong'), ('unit', 'Bo phan')], default='department', max_length=20),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_room',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='degree',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='license_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='license_issued_by',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='practice_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='scope_of_practice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='practice_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='professional_qualification',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='practice_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='professional_qualification',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='professional_rank',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='nurseprofile',
            name='shift',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('draft', 'Nhap'), ('issued', 'Da ke'), ('cancelled', 'Da huy')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='receptionistprofile',
            name='assigned_area',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='receptionistprofile',
            name='career_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receptionistprofile',
            name='handles_health_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('active_ingredient', models.CharField(max_length=160)),
                ('strength', models.CharField(max_length=80)),
                ('dosage_form', models.CharField(max_length=80)),
                ('unit', models.CharField(max_length=40)),
                ('route', models.CharField(choices=[('oral', 'Duong uong'), ('topical', 'Dung ngoai'), ('inhalation', 'Duong hit'), ('injection', 'Duong tiem'), ('other', 'Khac')], max_length=20)),
            ],
            options={
                'ordering': ['name', 'strength'],
                'indexes': [models.Index(fields=['name'], name='emrapi_medi_name_8b9965_idx'), models.Index(fields=['active_ingredient'], name='emrapi_medi_active__1c70f0_idx')],
            },
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescription_items', to='emrapi.medication'),
        ),
        migrations.AddConstraint(
            model_name='prescriptionitem',
            constraint=models.UniqueConstraint(fields=('prescription', 'medication'), name='unique_medication_per_prescription'),
        ),
    ]
