# Generated by Django 6.0.7 on 2026-07-25 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrapi', '0002_alter_department_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='department',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='department',
            name='unit_type',
        ),
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='medicine_name',
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Tao moi'), ('view', 'Xem'), ('update', 'Cap nhat'), ('delete', 'Xoa'), ('login', 'Dang nhap'), ('login_failed', 'Dang nhap that bai'), ('logout', 'Dang xuat')], max_length=20)),
                ('resource_type', models.CharField(max_length=120)),
                ('resource_id', models.CharField(blank=True, max_length=64, null=True)),
                ('resource_repr', models.CharField(blank=True, max_length=255, null=True)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('request_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', 'created_at'], name='emrapi_audi_actor_i_f128da_idx'), models.Index(fields=['action', 'created_at'], name='emrapi_audi_action_81b9ea_idx'), models.Index(fields=['resource_type', 'resource_id'], name='emrapi_audi_resourc_ac3f14_idx')],
            },
        ),
    ]
