# Generated by Django 6.0.7 on 2026-07-25 17:49

import emrapi.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrapi', '0003_alter_department_options_remove_department_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='license_issue_date',
            field=models.DateField(blank=True, null=True, validators=[emrapi.validators.validate_not_future_date]),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='practice_start_date',
            field=models.DateField(blank=True, null=True, validators=[emrapi.validators.validate_not_future_date]),
        ),
        migrations.AlterField(
            model_name='labtechnicianprofile',
            name='practice_start_date',
            field=models.DateField(blank=True, null=True, validators=[emrapi.validators.validate_not_future_date]),
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='practice_start_date',
            field=models.DateField(blank=True, null=True, validators=[emrapi.validators.validate_not_future_date]),
        ),
        migrations.AlterField(
            model_name='receptionistprofile',
            name='career_start_date',
            field=models.DateField(blank=True, null=True, validators=[emrapi.validators.validate_not_future_date]),
        ),
    ]
