# Generated by Django 6.0.7 on 2026-08-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emrapi', '0007_add_lab_test_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='status',
            field=models.CharField(choices=[('checked_in', 'Chờ đo sinh hiệu'), ('vitals_done', 'Đã đo sinh hiệu'), ('in_progress', 'Đang khám'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='checked_in', max_length=20),
        ),
    ]
